* Notes

Sky eye
El proyecto es un pequeño kit replicable para conectarse por radio con satelites climatologicos como los noaa 15,noaa 18, noaa 19 cubriendo zonas donde no llege el internet, Para observar cambios, anomalisas con IA en las zonas que cubre.

el kit tiene un panel solar para que sea energeticamente independiente

Es imporante tambien que sea independiente al internet para que pueda llegar a zonas mas remotas y facilitar al publico que no cuenta con estos recursos , como africa , el congo u otros.

En el caso que no tenga acceso a internet contara con un horario programable para conectarse con los satelites cuando pasen y limpiar los datos.

Si cuenta con acceso a internet tendra acceso a una interfas web.

la idea del proyecto es que sea accesible y replicable usando materiales de bajo costo y tecnologias libres.

El software se montara sobre una raspberry pi, con raspbian, ejecutando scripts de bash y python .



* para entregar

Agree to and check the boxs

entregarlo en la plataforma space apps

tener una demostracion del proyecto

*** demostracion  -> video de maximo 7 segundos o diapositivas maximo 7


* criterios a evaluar

Impact, Creativity,Validity, Relevance, and Presentation. 


* entrega

** proyect name

   lambda orbit sky eye
   
** wich is the problem

is 
with owrs perspective the problem is the acc

** solution
